version: "3"
services:
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-assess-risk-and-needs-oauth
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/auth/health"]
    environment:
      - SERVER_PORT=9091
      - SPRING_PROFILES_ACTIVE=dev

  postgres:
    image: postgres
    restart: always
    container_name: hmpps-assess-risk-and-needs-postgres
    ports:
      - 5432:5432
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

networks:
  hmpps: