---
# Per environment values which override defaults in hmpps-assess-risks-and-needs/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    contextColour: green
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "0"

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    ASSESSMENT_API_BASE_URL: https://offender-prprod.aks-live-1.studio-hosting.service.justice.gov.uk
    COMMUNITY_API_BASE_URL: https://arns-and-delius-preprod.hmpps.service.justice.gov.uk
    OASYS_API_BASE_URL: https://pp.oasys.service.justice.gov.uk/eor/oasys
    SENTRY_ENVIRONMENT: "preprod"
    SPRING_PROFILES_ACTIVE: "logstash,postgres,oasys-rsr"
generic-prometheus-alerts:
  enabled: false

dataExtractor:
  enabled: true
