---
# Per environment values which override defaults in hmpps-assess-risks-and-needs/values.yaml

service:
  replicaCount: 2

  ingress:
    host: hmpps-assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
